version: 0.2
env:
  variables:
    APP_NAME: "DVJA-SSC"
    APP_VERSION: "2.0"
  parameter-store:
    FORTIFY_SC_URL: "/fortify/sc_url"
    FORTIFY_CI_TOKEN: "/fortify/ci_token" 
    FORTIFY_SC_CLIENT_AUTH: "/fortify/sc_client_auth"
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - dotnet restore AspNetCoreWebApplication/aspnet-core-dotnet-core.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output AspNetCoreWebApplication/aspnet-core-dotnet-core.csproj
#      - dotnet vstest AspNetCoreWebApplicationTest/bin/release/netcoreapp3.1/AspNetCoreWebApplicationTest.dll
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
      ###########################################################################################
      #                     INJECT FORTIFY SAST SCRIPT                                          #
      # FOR SCA = fortify_sast_dotnet_template, FOR SCANCENTRAL = fortify_sc_dotnet_template    #
      ##########################################################################################
      - bash ./fortify_sc_dotnet_template.bash
artifacts:
  files:
    - template.yml
    - AspNetCoreWebApplication/**/*
    - scripts/**/*
    - appspec.yml
    - requirements.txt
    - template-configuration.json
