steps:
- name: 'python:3.9'
  args: ['python', '-m', 'pip', 'install', '-r', 'requirements.txt', '--user']
  
- name: 'python'
  ###################################################
  #             INTEGRATE FORTIFY SAST              #
  #                                                 #
  # For FORTIFY ON DEMAND uncomment the next line   #
  #args: ['bash', './fortify_sast_fod_python_template.bash']
  #                                                 #
  # For FORTIFY SCANCENTRAL uncomment the next line #
  #args: ['bash', './fortify_sast_scancentral_python_template.bash']
  #                                                 #
  ###################################################
  args: ['bash', './fortify_sast_fod_python_template.bash']
  env:
    #- 'FORTIFY_SC_URL=${_SC_URL}' 
    #- 'FORTIFY_CI_TOKEN=${_SC_CI_TOKEN}' 
    #- 'APP_NAME=${_SC_APP_NAME}' 
    #- 'APP_VERSION=${_SC_APP_VERSION}' 
    #- 'FORTIFY_SC_CLIENT_AUTH=${_SC_CLIENT_TOKEN}' 
    - 'FOD_BASEURL=${_FOD_URL}'
    - 'FOD_RELEASE_ID=${_FOD_APP_RELEASE_ID}'
    - 'FOD_TENANT=${_FOD_TENANT}' 
    - 'FOD_USER=${_FOD_USER}'
    - 'FOD_PWD=${_FOD_PWD}'
timeout: 2400s