version: 0.2
env:
  variables:
    FOD_BASEURL: "https://ams.fortify.com"
    FOD_RELEASE_ID: "343966"
  parameter-store:
    FOD_TENANT: "/fod/tenant"
    FOD_USER: "/fod/user"
    FOD_PWD: "/fod/pwd"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      #- mvn clean compile test
      - mvn clean
  build:
    commands:
      - mvn package
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
      ###########################################################################################
      #                     INJECT FORTIFY ON DEMAND SAST SCRIPT                                #
      #                         FOR SAST = fod_sast_template                                    #
      ##########################################################################################
      - bash fod_sast_template.bash
artifacts:
  files:
    - 'appspec.yml'
    - 'template.yml'
    - 'scripts/*'
    - 'target/ROOT.war'
    - 'template-configuration.json'
